typography_spectrum: 0.6568774008192122
color:
  brandStrength: 0.8669764951337129
  lightness: 0.7014711771626025
  saturation: 0.5946272471919656
  rhythmicContrast: 0.18709076708182693
  brandColors:
    - '#000000'
    - '#FBFBFB'
    - '#D8C9C2'
    - '#996A3C'
    - '#3F1C08'
layout_spectrum: 0.19525923230685294
analytics:
  facebook: '212457149155465'
author:
  name: David Beasley
  email: nybwgridwork@gmail.com
name: New York Bass Works LLC
navigation:
  - name: About Us
    id: eb391c06-531f-4850-985a-e61e676cb33c
    type: content
  - name: Contact us
    id: 54897aea-ee6e-411a-a514-4d33ef2ac04a
    type: content
  - name: Models
    id: 0100e19b-f423-4f7d-a669-cd63311d9494
    type: content
title: 'New York Bass Works '
description: The threshold of your instrument should be just beyond your grasp!
