typography_spectrum: 0.9760488651227206
color:
  brandStrength: 0.02072698506526649
  lightness: 0.8505153756123036
  saturation: 0.6945775840431452
  rhythmicContrast: 0.23767928197048604
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.11162845836952329
analytics:
  facebook: '212457149155465'
author:
  name: David Beasley
  email: nybwgridwork@gmail.com
name: New York Bass Works LLC
navigation:
  - name: About Us
    id: eb391c06-531f-4850-985a-e61e676cb33c
    type: content
title: 'New York Bass Works '
description: The threshold of your instrument should be just beyond your grasp
